name: release

# This workflow requires a GALAXY_API_KEY secret to be defined in the GitHub
# repository settings.

on:
  push:
    branches: [main]
    paths-ignore:
      - tests/**
      - LICENSE

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release Ansible Role to Galaxy
        uses: hspaans/ansible-galaxy-action@v0.2.7
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
